### ISSUE TITLE
ReactMusic + react-native-slider code issue in seekbar.js @line 42/43

### ISSUE THREAD

**Issue by BryonConley** [aakashns/ReactMusic#11]
Hello Aakash,

THank you for putting together a well thought out react-native project.   I know this is slightly old since the last issue update, but if this is still actively maintained. I do have an issue with the react-native-slider and <slider tag in the seekbar.js code segment.   Specifically the error message copied from the react-native log window that comes up during "react-native run-android" command which did load the code into the android emulator, but fails due to  the following message:
To reload the app press "r"
To open developer menu press "d"

[Tue Aug 18 2020 23:02:03.493]  BUNDLE  ./index.android.js

[Tue Aug 18 2020 23:02:11.342]  LOG      Running "ReactMusic" with {"rootTag":1}
[Tue Aug 18 2020 23:02:11.345]  ERROR    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at SeekBar.js:43.
    in SeekBar (at Player.js:104)
    in RCTView (at View.js:34)
    in View (at Player.js:99)
    in Player (at App.js:27)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Tue Aug 18 2020 23:02:11.346]  ERROR    Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `SeekBar`.

This error is loca

After doing some investigation, it appears to have something with the neweer version of the react-native-slider vers 0.11 compared to your version you used as 0.7.+ and in conjunction to  the different version fo react-native I am using (current).  Please find the package.json contents below for reference between the one you have and the one I have:
"name": "ReactMusic",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-slider": "^0.11.0",
    "react-native-video": "^5.1.0-alpha7"
  },
  "devDependencies": {
    "@babel/core": "7.11.1",
    "@babel/runtime": "7.11.2",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },

Any advice on fixing this issue?   I suspect I may have a similar elsewhere like the react-native-video if this is related to the versions between react-native and the added packages.  Thank you again in advance for taking a look at the issue in advance.

**Comment by TienNguyenanh** [comment]
in the SeekBar.js file, change:
from: var Slider = require('react-native-slider');
to: import Slider from "react-native-slider"
Hope to help you

**Comment by BryonConley** [comment]
Thank you Tien.   That is exactly what I wound up doing to get it to work.   I appreciate the feedback and confirming the solution.   Thank you again.
